### ISSUE TITLE
could not select device driver "" with capabilities: [[gpu]]

### ISSUE THREAD

**Issue by locnd** [fboulnois/stable-diffusion-docker#82]
setup is ok, but error when run
`./build.sh run 'Andromeda galaxy in a bottle'
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].`

I'm using Ubuntu 22.04.02 LTS
Core i7-1195G7
RAM 16GB
Graphics Mesa Intel® Xe Graphics (TGL GT2)
Disk Capacity 512,1GB

Please help!
Thanks!

**Comment by fboulnois** [comment]
Do you have an Nvidia GPU?

> **Minimum requirements**
> By default, the pipeline uses the full model and weights which requires a CUDA capable GPU with 8GB+ of VRAM. It should take a few seconds to create one image. On less powerful GPUs you may need to modify some of the options; see the [Examples](https://github.com/fboulnois/stable-diffusion-docker#examples) section for more details. If you lack a suitable GPU you can set the options --device cpu and --onnx instead.

**Comment by locnd** [comment]
@fboulnois 
thanks for your quick reply and so sorry for missing this piece.

I tried "-device cpu" and it works.
Thank you again !!!
